language: java
matrix:
  include:
    - language: java
      jdk: oraclejdk8
    - language: java
      jdk: oraclejdk7

notifications:
  email:
    recipients:
      - albgomceb@alum.us.es
    on_success: change # default: change
    on_failure: change # default: always
