language: java
include:
  - language: java
    jdk: oraclejdk8
  - language: java
    jdk: oraclejdk7

notifications:
  email:
    recipients:
      - crigalbla@alum.us.es
    on_success: change # default: change
    on_failure: change # default: always
