language: java
matrix:
  include:
    - language: java
      jdk: oraclejdk8

notifications:
  email:
    recipients:
      - crigalbla@alum.us.es
    on_success: change # default: change
    on_failure: change # default: always
